### ISSUE TITLE
    ss_dist_s_s = ss_dist_s(ss_id);

### ISSUE THREAD

**Issue by ogru** [Raphael-Nussbaumer-PhD/SGS#1]
Hello, 

Nice work on the code! 

I wanted to let you know that the conditional simulation code fails on line 141 with the following error:

Undefined function 'ss_dist_s' for input arguments of type 'double'.

Error in SGS_cst_par_cond (line 141)
    ss_dist_s_s = ss_dist_s(ss_id);

Regards,

**Comment by Rafnuss** [comment]
True, corrected with #9fdb036.
Let me know if you have any other problem. I don't think anyone has used it yet.
I'll mark the issue as close for now.
